version: '3.8'

services:
  coupon-bot:
    # 构建镜像，上下文为当前目录
    build: .
    # 容器的名称
    container_name: discord-coupon-bot
    # 设置重启策略
    # unless-stopped: 除非手动停止，否则容器总会自动重启
    restart: unless-stopped
    # 将宿主机的 .env 文件挂载到容器中，以便机器人能读取到 TOKEN
    # 请确保您的 .env 文件和 docker-compose.yml 在同一目录下
    volumes:
      - ./.env:/app/.env
      # 将宿主机的 ./data 目录挂载到容器的 /app/data 目录
      # 这是最直接的持久化方式，数据文件将直接出现在您的项目文件夹中
      - ./data:/app/data
      # 挂载备份目录，确保备份文件也能持久化
      - ./backups:/app/backups
    # <<< 新增：资源限制配置
    deploy:
      resources:
        limits:
          # 限制最多使用 0.5 个 CPU核心
          cpus: '0.5'
          # 限制最多使用 256MB 内存
          memory: 256M
        reservations:
          # 启动时为它预留 64MB 内存
          memory: 64M